name: Hexo Deploy

# 监听分支
on:
  push:
    branches:
      - hexo

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # 主题文件夹，如果你的主题不是 git submodule 可以不配置
      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: jerryc127/hexo-theme-butterfly
          ref: master
          path: themes/butterfly
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: | 
          npm install
          npm install -g hexo-cli
          npm install hexo-deployer-git --save
          npm install hexo-asset-image --save
          npm install hexo-wordcount --save
          npm install hexo-butterfly-artitalk
          npm install hexo-generator-search --save
	  npm install hexo-douban --save
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
